"""init database

Revision ID: 6a14e94c221e
Revises: 
Create Date: 2022-07-27 11:42:42.585131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a14e94c221e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=False),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('requirement', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_department'), 'positions', ['department'], unique=False)
    op.create_index(op.f('ix_positions_location'), 'positions', ['location'], unique=False)
    op.create_index(op.f('ix_positions_name'), 'positions', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('apply',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('base_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('sex', sa.String(length=8), nullable=False),
    sa.Column('race', sa.String(length=16), nullable=False),
    sa.Column('id_number', sa.String(length=18), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('educations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('degree', sa.String(length=32), nullable=False),
    sa.Column('school', sa.String(length=32), nullable=False),
    sa.Column('major', sa.String(length=32), nullable=False),
    sa.Column('begin_date', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone_number', sa.String(length=16), nullable=False),
    sa.Column('work', sa.String(length=32), nullable=False),
    sa.Column('relation', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company', sa.String(length=32), nullable=False),
    sa.Column('position', sa.String(length=32), nullable=False),
    sa.Column('begin_date', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.String(length=16), nullable=False),
    sa.Column('describe', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('works')
    op.drop_table('families')
    op.drop_table('educations')
    op.drop_table('base_info')
    op.drop_table('apply')
    op.drop_table('users')
    op.drop_index(op.f('ix_positions_name'), table_name='positions')
    op.drop_index(op.f('ix_positions_location'), table_name='positions')
    op.drop_index(op.f('ix_positions_department'), table_name='positions')
    op.drop_table('positions')
    # ### end Alembic commands ###
