"""disable userid null

Revision ID: fa29e0671808
Revises: 338106d31d78
Create Date: 2022-07-28 16:38:19.786913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa29e0671808'
down_revision = '338106d31d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apply', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('apply', 'position_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('educations', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('families', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('works', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('families', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('educations', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('apply', 'position_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('apply', 'user_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
